In [6]:
import numpy as np
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
tickers = ["AAPL", "MSFT"]

data = yf.download(
    tickers,
    start = "2021-01-01",
    end = "2026-01-01",
    auto_adjust = False
)

data.head()

[*********************100%***********************]  2 of 2 completed

Price        Adj Close                   Close                    High  \
Ticker            AAPL        MSFT        AAPL        MSFT        AAPL
Date
2021-01-04  125.632492  207.565399  129.410004  217.690002  133.610001
2021-01-05  127.185799  207.765610  131.009995  217.899994  131.740005
2021-01-06  122.904533  202.378418  126.599998  212.250000  131.050003
2021-01-07  127.098412  208.137482  130.919998  218.289993  131.630005
2021-01-08  128.195450  209.405594  132.050003  219.619995  132.630005

Price                          Low                    Open              \
Ticker            MSFT        AAPL        MSFT        AAPL        MSFT
Date
2021-01-04  223.000000  126.760002  214.809998  133.520004  222.529999
2021-01-05  218.520004  128.429993  215.699997  128.889999  217.259995
2021-01-06  216.490005  126.379997  211.940002  127.720001  212.169998
2021-01-07  219.339996  127.860001  213.710007  128.360001  214.039993
2021-01-08  220.580002  130.229996  217.029999  132.429993  218.679993

Price          Volume
Ticker           AAPL      MSFT
Date
2021-01-04  143301900  37130100
2021-01-05   97664900  23823000
2021-01-06  155088000  35930700
2021-01-07  109578200  27694500
2021-01-08  105158200  22956200

## 1. Data Inspection

In [12]:
data.shape

(1255, 12)

In [10]:
data.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 1255 entries, 2021-01-04 to 2025-12-31
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   (Adj Close, AAPL)  1255 non-null   float64
 1   (Adj Close, MSFT)  1255 non-null   float64
 2   (Close, AAPL)      1255 non-null   float64
 3   (Close, MSFT)      1255 non-null   float64
 4   (High, AAPL)       1255 non-null   float64
 5   (High, MSFT)       1255 non-null   float64
 6   (Low, AAPL)        1255 non-null   float64
 7   (Low, MSFT)        1255 non-null   float64
 8   (Open, AAPL)       1255 non-null   float64
 9   (Open, MSFT)       1255 non-null   float64
 10  (Volume, AAPL)     1255 non-null   int64
 11  (Volume, MSFT)     1255 non-null   int64
dtypes: float64(10), int64(2)
memory usage: 127.5 KB

In [13]:
data.isna().sum()

Price      Ticker
Adj Close  AAPL      0
           MSFT      0
Close      AAPL      0
           MSFT      0
High       AAPL      0
           MSFT      0
Low        AAPL      0
           MSFT      0
Open       AAPL      0
           MSFT      0
Volume     AAPL      0
           MSFT      0
dtype: int64

In [14]:
data.head()

Price        Adj Close                   Close                    High  \
Ticker            AAPL        MSFT        AAPL        MSFT        AAPL
Date
2021-01-04  125.632492  207.565399  129.410004  217.690002  133.610001
2021-01-05  127.185799  207.765610  131.009995  217.899994  131.740005
2021-01-06  122.904533  202.378418  126.599998  212.250000  131.050003
2021-01-07  127.098412  208.137482  130.919998  218.289993  131.630005
2021-01-08  128.195450  209.405594  132.050003  219.619995  132.630005

Price                          Low                    Open              \
Ticker            MSFT        AAPL        MSFT        AAPL        MSFT
Date
2021-01-04  223.000000  126.760002  214.809998  133.520004  222.529999
2021-01-05  218.520004  128.429993  215.699997  128.889999  217.259995
2021-01-06  216.490005  126.379997  211.940002  127.720001  212.169998
2021-01-07  219.339996  127.860001  213.710007  128.360001  214.039993
2021-01-08  220.580002  130.229996  217.029999  132.429993  218.679993

Price          Volume
Ticker           AAPL      MSFT
Date
2021-01-04  143301900  37130100
2021-01-05   97664900  23823000
2021-01-06  155088000  35930700
2021-01-07  109578200  27694500
2021-01-08  105158200  22956200

In [15]:
data.tail()

Price        Adj Close                   Close                    High  \
Ticker            AAPL        MSFT        AAPL        MSFT        AAPL
Date
2025-12-24  273.066711  484.943420  273.809998  488.019989  275.429993
2025-12-26  272.657837  484.635406  273.399994  487.709991  275.369995
2025-12-29  273.016876  484.029236  273.760010  487.100006  274.359985
2025-12-30  272.338715  484.406860  273.079987  487.480011  274.079987
2025-12-31  271.122009  480.571167  271.859985  483.619995  273.679993

Price                          Low                    Open              \
Ticker            MSFT        AAPL        MSFT        AAPL        MSFT
Date
2025-12-24  489.160004  272.200012  484.829987  272.339996  485.679993
2025-12-26  488.119995  272.859985  485.959991  274.160004  486.709991
2025-12-29  488.350006  272.350006  484.179993  272.690002  484.859985
2025-12-30  489.679993  272.279999  485.500000  272.809998  485.929993
2025-12-31  488.140015  271.750000  483.299988  273.059998  487.839996

Price         Volume
Ticker          AAPL      MSFT
Date
2025-12-24  17910600   5855900
2025-12-26  21521800   8842200
2025-12-29  23715200  10893400
2025-12-30  22139600  13944500
2025-12-31  27293600  15601600

In [18]:
data.index

DatetimeIndex(['2021-01-04', '2021-01-05', '2021-01-06', '2021-01-07',
               '2021-01-08', '2021-01-11', '2021-01-12', '2021-01-13',
               '2021-01-14', '2021-01-15',
               ...
               '2025-12-17', '2025-12-18', '2025-12-19', '2025-12-22',
               '2025-12-23', '2025-12-24', '2025-12-26', '2025-12-29',
               '2025-12-30', '2025-12-31'],
              dtype='datetime64[s]', name='Date', length=1255, freq=None)

In [19]:
data.index.min()

Timestamp('2021-01-04 00:00:00')

In [20]:
data.index.max()

Timestamp('2025-12-31 00:00:00')